// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_broker.proto

package goalgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogRequest struct {
	Sid                  int32    `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_802e9beed3ec3b28, []int{0}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *LogRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReply) Reset()         { *m = LogReply{} }
func (m *LogReply) String() string { return proto.CompactTextString(m) }
func (*LogReply) ProtoMessage()    {}
func (*LogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_802e9beed3ec3b28, []int{1}
}

func (m *LogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReply.Unmarshal(m, b)
}
func (m *LogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReply.Marshal(b, m, deterministic)
}
func (m *LogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReply.Merge(m, src)
}
func (m *LogReply) XXX_Size() int {
	return xxx_messageInfo_LogReply.Size(m)
}
func (m *LogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogReply proto.InternalMessageInfo

func (m *LogReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "goalgo.LogRequest")
	proto.RegisterType((*LogReply)(nil), "goalgo.LogReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RobotCtlClient is the client API for RobotCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RobotCtlClient interface {
	// 写入日志
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error)
}

type robotCtlClient struct {
	cc *grpc.ClientConn
}

func NewRobotCtlClient(cc *grpc.ClientConn) RobotCtlClient {
	return &robotCtlClient{cc}
}

func (c *robotCtlClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error) {
	out := new(LogReply)
	err := c.cc.Invoke(ctx, "/goalgo.RobotCtl/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotCtlServer is the server API for RobotCtl service.
type RobotCtlServer interface {
	// 写入日志
	Log(context.Context, *LogRequest) (*LogReply, error)
}

func RegisterRobotCtlServer(s *grpc.Server, srv RobotCtlServer) {
	s.RegisterService(&_RobotCtl_serviceDesc, srv)
}

func _RobotCtl_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotCtlServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goalgo.RobotCtl/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotCtlServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotCtl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goalgo.RobotCtl",
	HandlerType: (*RobotCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _RobotCtl_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_broker.proto",
}

func init() { proto.RegisterFile("grpc_broker.proto", fileDescriptor_802e9beed3ec3b28) }

var fileDescriptor_802e9beed3ec3b28 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x9c, 0x94, 0x70, 0x03, 0x2a, 0x27, 0x06, 0x8b, 0xc9, 0xca, 0xe4, 0x85, 0x0c,
	0x30, 0xb1, 0xb0, 0xb0, 0x76, 0xf2, 0x1f, 0x40, 0x4d, 0x72, 0xb2, 0x2c, 0x5c, 0x9d, 0xb1, 0x5d,
	0xa4, 0xfe, 0x7b, 0x54, 0x57, 0x15, 0x64, 0x7b, 0xef, 0x74, 0x9f, 0x9e, 0x3e, 0x78, 0x70, 0x29,
	0xce, 0x9f, 0x53, 0xe2, 0x2f, 0x4a, 0x63, 0x4c, 0x5c, 0x18, 0x37, 0x8e, 0xf7, 0xc1, 0xf1, 0x90,
	0x00, 0x76, 0xec, 0x2c, 0x7d, 0x1f, 0x29, 0x17, 0xdc, 0x82, 0xcc, 0x7e, 0x51, 0x42, 0x0b, 0xd3,
	0xd9, 0x73, 0xc4, 0x7b, 0x68, 0xfc, 0xa2, 0x1a, 0x2d, 0x4c, 0x6b, 0x1b, 0xbf, 0x20, 0x42, 0x5b,
	0xfc, 0x81, 0x94, 0xd4, 0xc2, 0x48, 0x5b, 0x33, 0x3e, 0x42, 0x17, 0xe8, 0x87, 0x82, 0x6a, 0x2b,
	0x77, 0x29, 0xa8, 0xe0, 0xf6, 0x40, 0x39, 0xef, 0x1d, 0xa9, 0x4e, 0x0b, 0x73, 0x67, 0xaf, 0x75,
	0x78, 0x87, 0xbe, 0x6e, 0xc6, 0x70, 0x3a, 0x7f, 0xe5, 0xe3, 0x3c, 0x53, 0xce, 0x75, 0xb5, 0xb7,
	0xd7, 0xfa, 0x9f, 0x6f, 0x56, 0xfc, 0xcb, 0x1b, 0xf4, 0x96, 0x27, 0x2e, 0x1f, 0x25, 0xe0, 0x33,
	0xc8, 0x1d, 0x3b, 0xc4, 0xf1, 0xe2, 0x33, 0xfe, 0xc9, 0x3c, 0x6d, 0x57, 0xb7, 0x18, 0x4e, 0xc3,
	0xcd, 0xb4, 0xa9, 0xf6, 0xaf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xb3, 0x37, 0x60, 0x12,
	0x01, 0x00, 0x00,
}
